"""
quote_generator.py
------------------
Generates pure text motivational quotes across 8 distinct categories:
- Philosophers (Marcus Aurelius, Seneca, Epictetus, Confucius, Lao Tzu)
- Movies (Fight Club, Interstellar, The Dark Knight, Good Will Hunting)
- Series (Peaky Blinders, Breaking Bad, Succession, Suits)
- Books (48 Laws of Power, Meditations, Art of War, Man's Search for Meaning)
- Cartoons (Avatar: The Last Airbender, BoJack Horseman, Gravity Falls)
- Anime (Vinland Saga, Naruto, Attack on Titan, Berserk, Haikyuu)
- Personalities (Steve Jobs, Kobe Bryant, Elon Musk, David Goggins, Naval Ravikant)
- AI Original (original deep motivational quotes generated by AI)

Model priority chain (with automatic fallback):
  1. Groq: groq/compound
  2. Groq: qwen/qwen3.6-27b
  3. Gemini: gemini-3.6-flash  (if GEMINI_API_KEY is set)
  4. Curated fallback dataset
"""

from __future__ import annotations

import json
import logging
import os
import random
import re
import sys
import textwrap
from typing import Optional

# Force UTF-8 output on Windows
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8', errors='replace')

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("quote_generator")

# ── Model Priority ────────────────────────────────────────────────────────────
GROQ_MODELS = [
    os.getenv("GROQ_MODEL", "groq/compound"),
    "llama-3.1-8b-instant",   # reliable free-tier fallback (qwen3.6-27b returns empty)
]
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")

CATEGORIES = [
    "philosophers",
    "movies",
    "series",
    "books",
    "cartoons",
    "anime",
    "personalities",
    "ai",
]

# ── Expanded Fallback Database ────────────────────────────────────────────────
FALLBACK_QUOTES = {
    "philosophers": [
        {"quote": "We suffer more often in imagination than in reality.", "author": "Seneca", "context": "Stop catastrophising — most fears never materialise."},
        {"quote": "You have power over your mind — not outside events. Realise this, and you will find strength.", "author": "Marcus Aurelius", "context": "Master your internal state first."},
        {"quote": "He who has a why to live can bear almost any how.", "author": "Friedrich Nietzsche", "context": "Purpose is the engine of endurance."},
        {"quote": "No man ever steps in the same river twice, for it's not the same river and he's not the same man.", "author": "Heraclitus", "context": "Change is the only constant — embrace it."},
        {"quote": "Waste no more time arguing about what a good man should be. Be one.", "author": "Marcus Aurelius", "context": "Action over philosophy — every time."},
        {"quote": "The obstacle is the way.", "author": "Marcus Aurelius (Ryan Holiday interpretation)", "context": "Every challenge is a hidden advantage."},
        {"quote": "Knowledge speaks, but wisdom listens.", "author": "Jimi Hendrix (popularised)", "context": "The wisest person in the room listens most."},
    ],
    "movies": [
        {"quote": "It's only after we've lost everything that we're free to do anything.", "author": "Tyler Durden (Fight Club)", "context": "Attachment is the cage — let go to find freedom."},
        {"quote": "Why do we fall? So that we can learn to pick ourselves up.", "author": "Alfred Pennyworth (The Dark Knight)", "context": "Failure is the syllabus, not the final exam."},
        {"quote": "Do not go gentle into that good night.", "author": "Dylan Thomas / Interstellar", "context": "Rage against mediocrity and surrender."},
        {"quote": "It's not who I am underneath, but what I do that defines me.", "author": "Bruce Wayne (Batman Begins)", "context": "Character is proven through action, not intent."},
        {"quote": "You'll have bad times, but it'll always wake you up to the good stuff you weren't paying attention to.", "author": "Sean Maguire (Good Will Hunting)", "context": "Pain sharpens your appreciation for beauty."},
    ],
    "series": [
        {"quote": "Lies are not a leverage. They are a vulnerability.", "author": "Thomas Shelby (Peaky Blinders)", "context": "Truth builds undeniable strength over time."},
        {"quote": "I am not in danger. I am the danger.", "author": "Walter White (Breaking Bad)", "context": "Own your presence — project power through clarity."},
        {"quote": "Succession is a game of inches. Every inch costs you everything.", "author": "Logan Roy (Succession)", "context": "Complacency is the enemy of legacy."},
        {"quote": "Winners are not people who never fail, but people who never quit.", "author": "Harvey Specter (Suits)", "context": "Resilience is the only sustainable strategy."},
    ],
    "books": [
        {"quote": "When you show yourself to the world and display your talents, you naturally stir all kinds of resentment.", "author": "Robert Greene (48 Laws of Power)", "context": "Master the art of strategic discretion."},
        {"quote": "In the midst of chaos, there is also opportunity.", "author": "Sun Tzu (The Art of War)", "context": "Seek the advantage inside every difficult situation."},
        {"quote": "Everything can be taken from a man but one thing: the last of human freedoms — to choose one's attitude.", "author": "Viktor Frankl (Man's Search for Meaning)", "context": "Your response to life is always your choice."},
        {"quote": "A man who procrastinates in his choosing will inevitably have his choice made for him by circumstance.", "author": "Hunter S. Thompson", "context": "Decide deliberately or drift by default."},
    ],
    "cartoons": [
        {"quote": "In the darkest times, hope is something you give yourself. That is the meaning of inner strength.", "author": "Uncle Iroh (Avatar: The Last Airbender)", "context": "Cultivate your own light — don't wait for the world."},
        {"quote": "It gets easier. Every day it gets a little easier. But you gotta do it every day.", "author": "Jogging Baboon (BoJack Horseman)", "context": "Discipline is built one rep at a time."},
        {"quote": "Just because something ends doesn't mean it never happened or that it wasn't good.", "author": "Stan Pines (Gravity Falls)", "context": "Gratitude reframes every ending as a gift."},
    ],
    "anime": [
        {"quote": "You have no enemies. No one has any enemies. There is no one that it is okay to hurt.", "author": "Thors (Vinland Saga)", "context": "True strength lies in the discipline of peace."},
        {"quote": "If you don't like your destiny, don't accept it. Instead, have the courage to change it.", "author": "Naruto Uzumaki (Naruto)", "context": "Defy your limitations — rewrite your story."},
        {"quote": "The world is cruel, but also very beautiful.", "author": "Mikasa Ackerman (Attack on Titan)", "context": "Hold both truths simultaneously — that is wisdom."},
        {"quote": "Cry in the dressing room. Go out on the court and be calm.", "author": "Kiyoko Shimizu (Haikyuu)", "context": "Professionalism means mastering your emotions, not suppressing them."},
    ],
    "personalities": [
        {"quote": "The people who are crazy enough to think they can change the world are the ones who do.", "author": "Steve Jobs", "context": "Embrace your bold ambition — logic alone never changed history."},
        {"quote": "Don't stop when you're tired. Stop when you're done.", "author": "David Goggins", "context": "Your body quits long before your potential does."},
        {"quote": "Earn with your mind, not your time.", "author": "Naval Ravikant", "context": "Leverage is the multiplier between effort and output."},
        {"quote": "Talent is obvious. Work ethic is rare.", "author": "Kobe Bryant", "context": "The rarest ingredient in success is consistent unglamorous effort."},
        {"quote": "The path to success is to take massive, determined action.", "author": "Tony Robbins", "context": "Planning without action is just productive procrastination."},
    ],
    "ai": [
        {"quote": "The quiet hours of preparation build the loud victories of tomorrow.", "author": "Navi AI", "context": "Work silently. Let results speak loudly."},
        {"quote": "Your potential expands the moment you stop asking for permission to grow.", "author": "Navi AI", "context": "Self-belief is the permission slip you've been waiting for."},
        {"quote": "Discipline is not punishment. It is the bridge between who you are and who you want to become.", "author": "Navi AI", "context": "Build the bridge one consistent action at a time."},
        {"quote": "The version of you that stops making excuses is the version of you that wins.", "author": "Navi AI", "context": "Excuses are sophisticated stories we tell ourselves."},
    ],
}

SYSTEM_PROMPT = textwrap.dedent("""\
    You are an expert curator of powerful, memorable quotes for viral social media content.
    Your audience is 18-35 years old and deeply values authenticity, depth, and originality.

    Generate ONE powerful quote from the requested category. Prioritise quotes that are:
    - LESSER-KNOWN or underused (avoid overposted quotes like "Be yourself" or "Work hard")
    - SPECIFIC to the source character/person/work
    - Emotionally resonant and shareable
    - Grammatically perfect and punchy

    Respond ONLY with a valid JSON object matching this schema (no markdown, no extra text):
    {
      "quote": "<The exact quote text>",
      "author": "<Full attribution, e.g. 'Thomas Shelby (Peaky Blinders)' or 'Marcus Aurelius'>",
      "category": "<Category name>",
      "context": "<1 short sentence of actionable reflection inspired by the quote>"
    }

    Rules:
    - Do NOT generate quotes from the same author twice in a row.
    - The context must be practical and original — not just a paraphrase of the quote.
    - Keep the quote under 200 characters where possible for social media fit.
    - Do NOT include any text outside the JSON object.
""")


def _format_x_post(quote: str, author: str, category: str) -> str:
    """Format quote for X (Twitter), strictly <= 280 characters."""
    cat_tag = f"#{category.replace(' ', '').capitalize()}" if category.lower() != "ai" else "#AIWisdom"
    base = f'"{quote}"\n\n— {author}\n\n#Motivation #Mindset {cat_tag}'
    if len(base) <= 280:
        return base
    max_q = 280 - len(f'"..."\n\n— {author}\n\n#Motivation #Mindset {cat_tag}')
    return f'"{quote[:max_q].rstrip()}..."\n\n— {author}\n\n#Motivation #Mindset {cat_tag}'


def _format_threads_post(quote: str, author: str, context: str, category: str) -> str:
    """Format quote for Threads, up to 500 characters."""
    cat_tag = f"#{category.replace(' ', '').capitalize()}" if category.lower() != "ai" else "#AIWisdom"
    post = f'"{quote}"\n\n— {author}\n\n💡 {context}\n\n#motivation #quotes #mindset {cat_tag}'
    return post[:500]


def _call_groq(selected_category: str) -> dict | None:
    """Try Groq models in order; return parsed dict or None."""
    groq_api_key = os.getenv("GROQ_API_KEY", "")
    if not groq_api_key:
        return None

    from groq import Groq
    client = Groq(api_key=groq_api_key)
    prompt = (
        f"Generate an iconic, lesser-known motivational quote from the category: '{selected_category}'. "
        f"Avoid overused quotes. Pick something surprising and specific."
    )

    # Compact system prompt to stay well under token limits
    compact_system = (
        "You are an expert quote curator for viral social media. "
        "Generate ONE powerful, lesser-known motivational quote from the requested category. "
        "Avoid overused quotes. Be specific and surprising. "
        "Respond ONLY with a valid JSON object: "
        '{"quote": "<quote text>", "author": "<full attribution>", "category": "<category>", "context": "<1 short actionable sentence>"}'
    )

    for model_name in GROQ_MODELS:
        try:
            logger.info("Calling Groq (%s) for quote category: %s", model_name, selected_category)
            response = client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": compact_system},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.88,
                max_tokens=300,
            )
            raw = response.choices[0].message.content.strip()
            raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
            raw = re.sub(r"^```(?:json)?", "", raw, flags=re.IGNORECASE)
            raw = re.sub(r"```$", "", raw).strip()
            if not raw:
                logger.warning("Groq (%s) returned empty response.", model_name)
                continue
            data = json.loads(raw)
            if data.get("quote") and data.get("author"):
                logger.info("Groq (%s) quote generation succeeded.", model_name)
                return data
        except Exception as exc:
            logger.warning("Groq model %s failed: %s", model_name, exc)

    return None


def _call_gemini(selected_category: str) -> dict | None:
    """Fallback to Gemini REST API."""
    gemini_key = os.getenv("GEMINI_API_KEY", "")
    if not gemini_key:
        return None

    import urllib.request
    prompt = (
        f"{SYSTEM_PROMPT}\n\n"
        f"Generate an iconic, lesser-known motivational quote from the category: '{selected_category}'."
    )
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={gemini_key}"
    payload = json.dumps({
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.88, "maxOutputTokens": 400},
    }).encode()

    try:
        req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=20) as resp:
            result = json.loads(resp.read())
            raw = result["candidates"][0]["content"]["parts"][0]["text"].strip()
            raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
            raw = re.sub(r"^```(?:json)?", "", raw, flags=re.IGNORECASE)
            raw = re.sub(r"```$", "", raw).strip()
            data = json.loads(raw)
            if data.get("quote") and data.get("author"):
                logger.info("Gemini fallback quote generation succeeded.")
                return data
    except Exception as exc:
        logger.warning("Gemini quote fallback failed: %s", exc)

    return None


def generate_quote(category: str | None = None) -> dict:
    """
    Generate a motivational quote from specified or random category.

    Returns dict with keys: quote, author, category, context,
                            formatted_x_post, formatted_threads_post
    """
    selected_category = (category or "").lower().strip()
    if selected_category not in CATEGORIES:
        selected_category = random.choice(CATEGORIES)

    logger.info("Generating motivational quote for category: %s", selected_category)

    # 1. Try Groq
    data = _call_groq(selected_category)

    # 2. Try Gemini
    if not data:
        logger.info("Groq failed, trying Gemini...")
        data = _call_gemini(selected_category)

    # 3. Curated fallback dataset
    if not data:
        logger.warning("All APIs failed — using curated fallback for: %s", selected_category)
        pool = FALLBACK_QUOTES.get(selected_category, FALLBACK_QUOTES["philosophers"])
        item = random.choice(pool)
        data = {
            "quote": item["quote"],
            "author": item["author"],
            "category": selected_category,
            "context": item["context"],
        }

    quote   = data.get("quote", "").strip()
    author  = data.get("author", "Unknown").strip()
    context = data.get("context", "Reflect on this wisdom today.").strip()

    return {
        "quote":                 quote,
        "author":                author,
        "category":              selected_category,
        "context":               context,
        "formatted_x_post":      _format_x_post(quote, author, selected_category),
        "formatted_threads_post": _format_threads_post(quote, author, context, selected_category),
    }


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    q = generate_quote("anime")
    print("--- X POST ---")
    print(q["formatted_x_post"])
    print("\n--- THREADS POST ---")
    print(q["formatted_threads_post"])
